name: Update News
on:
  schedule:
    - cron: '*/30 * * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ရေးခွင့်ပေးရန်
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          # cache: 'pip' ကို ဖြုတ်လိုက်ပြီ ဖြစ်၍ requirements.txt မလိုတော့ပါ

      - name: Install dependencies
        run: |
          pip install feedparser beautifulsoup4 requests lxml

      - name: Fetch news data
        run: python fetch_news.py

      - name: Commit and Push
        run: |
          git config --global user.name 'NewsBot'
          git config --global user.email 'bot@news.com'
          git add news.json
          # အပြောင်းအလဲရှိမှသာ commit လုပ်ပြီး push မည်
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update News: $(date)" && git push)
